# Generated by Django 4.1 on 2022-08-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(default='default title', max_length=10)),
                ('work_process', models.CharField(default='default title', max_length=50)),
                ('model_equipment', models.CharField(default='default title', max_length=50)),
                ('node_equipment', models.CharField(default='default title', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Spare_part_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part_name', models.CharField(default='default title', max_length=90)),
                ('type_part', models.CharField(default='default title', max_length=90)),
                ('manufacturer', models.CharField(default='default title', max_length=50)),
                ('criticality', models.PositiveSmallIntegerField(default='default title')),
                ('sap_Code1', models.PositiveIntegerField(default='default title')),
                ('sap_Code2', models.PositiveIntegerField(default='default title')),
                ('sap_analog', models.PositiveIntegerField(default='default title')),
                ('min_count', models.PositiveIntegerField(default='default title')),
                ('max_count', models.PositiveIntegerField(default='default title')),
                ('for_order', models.PositiveIntegerField(default='default title')),
            ],
        ),
        migrations.CreateModel(
            name='Belonging_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_temp', models.CharField(default='default title', max_length=90)),
                ('belonging_equipment_key_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.equipment_list')),
                ('belonging_equipment_key_spareparts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.spare_part_list')),
            ],
        ),
    ]
