# Generated by Django 4.1 on 2022-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0002_rename_equipment_list_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sup_emul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.PositiveIntegerField(default='default title')),
                ('sap_name', models.CharField(default='default title', max_length=90)),
                ('sap_warehouse', models.CharField(default='default title', max_length=90)),
                ('sap_end_point', models.CharField(default='default title', max_length=90)),
                ('sap_count', models.PositiveIntegerField(default='default title')),
                ('sap_unit', models.CharField(default='default title', max_length=90)),
                ('sap_price', models.PositiveIntegerField(default='default title')),
                ('sap_currency', models.CharField(default='default title', max_length=90)),
            ],
        ),
    ]
