# Generated by Django 4.1 on 2022-08-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0004_alter_sup_emul_sap_code_alter_sup_emul_sap_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spare_part_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_part_name', models.CharField(default='default title', max_length=90)),
                ('type_part', models.CharField(default='default title', max_length=90)),
                ('manufacturer', models.CharField(default='default title', max_length=50)),
                ('criticality', models.PositiveSmallIntegerField(default='default title')),
                ('sap_Code1', models.PositiveIntegerField(default='default title')),
                ('sap_Code2', models.PositiveIntegerField(default='default title')),
                ('sap_analog', models.PositiveIntegerField(default='default title')),
                ('min_count', models.PositiveIntegerField(default='default title')),
                ('max_count', models.PositiveIntegerField(default='default title')),
                ('for_order', models.PositiveIntegerField(default='default title')),
                ('who_creat', models.CharField(default='default title', max_length=90)),
                ('was_moderated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='belonging_equipment',
            name='name_temp',
        ),
    ]
