# Generated by Django 4.1 on 2022-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0005_spare_part_add_remove_belonging_equipment_name_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part_add',
            name='criticality',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='for_order',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='max_count',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='min_count',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='sap_Code1',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='sap_Code2',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='sap_analog',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='who_creat',
            field=models.CharField(max_length=90),
        ),
    ]
