# Generated by Django 4.1 on 2022-09-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0007_genre_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
