# Generated by Django 4.1 on 2022-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0008_delete_film_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='was_moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_equipment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='node_equipment',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specialty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='work_process',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='criticality',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='for_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='max_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='min_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_analog',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='type_part',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='spare_part_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='spare_part_add',
            name='type_part',
            field=models.CharField(max_length=90),
        ),
    ]
