# Generated by Django 4.1 on 2022-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0009_spare_part_was_moderated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Spare_part_add',
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='max_count',
        ),
        migrations.RemoveField(
            model_name='spare_part',
            name='min_count',
        ),
        migrations.AddField(
            model_name='belonging_equipment',
            name='max_count',
            field=models.PositiveIntegerField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='belonging_equipment',
            name='min_count',
            field=models.PositiveIntegerField(null='true'),
            preserve_default='true',
        ),
    ]
