# Generated by Django 4.1 on 2022-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0010_delete_spare_part_add_remove_spare_part_max_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_from_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_imp', models.PositiveIntegerField(blank='true')),
                ('sup_imp', models.PositiveIntegerField(blank='true')),
                ('analog_imp', models.PositiveIntegerField(blank='true')),
                ('localiz_imp', models.CharField(blank='true', max_length=90)),
                ('alt_sup_imp', models.PositiveIntegerField(blank='true')),
                ('naimen_imp', models.CharField(blank='true', max_length=90)),
                ('tip_imp', models.CharField(blank='true', max_length=90)),
                ('proc_imp', models.CharField(blank='true', max_length=90)),
                ('model_obor_imp', models.CharField(blank='true', max_length=90)),
                ('uzel_imp', models.CharField(blank='true', max_length=90)),
                ('edin_izm_imp', models.CharField(blank='true', max_length=90)),
                ('summ_kol_imp', models.PositiveIntegerField(blank='true')),
                ('min_imp', models.PositiveIntegerField(blank='true')),
                ('max_imp', models.PositiveIntegerField(blank='true')),
                ('ver_polomki_imp', models.PositiveIntegerField(blank='true')),
                ('vliyanie_imp', models.PositiveIntegerField(blank='true')),
                ('obshiy_krit_imp', models.PositiveIntegerField(blank='true')),
                ('meh_el_imp', models.CharField(blank='true', max_length=90)),
            ],
        ),
    ]
