# Generated by Django 4.1 on 2022-09-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0011_import_from_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_from_excel',
            name='proizv_imp',
            field=models.CharField(blank='true', max_length=90),
        ),
    ]
