# Generated by Django 4.1 on 2022-09-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0012_import_from_excel_proizv_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='alt_sup_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='analog_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='edin_izm_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='localiz_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='max_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='meh_el_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='min_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='model_obor_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='naimen_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='number_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='obshiy_krit_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='proc_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='proizv_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='summ_kol_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='sup_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='tip_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='uzel_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='ver_polomki_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='vliyanie_imp',
            field=models.PositiveIntegerField(null='true'),
        ),
    ]
