# Generated by Django 4.1 on 2022-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0013_alter_import_from_excel_alt_sup_imp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='criticality',
            field=models.PositiveSmallIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='for_order',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code1',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code2',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_analog',
            field=models.PositiveIntegerField(null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_name',
            field=models.CharField(max_length=90, null='true'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='type_part',
            field=models.CharField(max_length=90, null='true'),
        ),
    ]
