# Generated by Django 4.1 on 2022-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0014_alter_spare_part_criticality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belonging_equipment',
            name='max_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='belonging_equipment',
            name='min_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='criticality',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='for_order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_analog',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='type_part',
            field=models.CharField(max_length=90),
        ),
    ]
