# Generated by Django 4.1 on 2022-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0015_alter_belonging_equipment_max_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='criticality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='for_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code1',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code2',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_analog',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='spare_part_name',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='type_part',
            field=models.CharField(default='', max_length=90),
        ),
    ]
