# Generated by Django 4.1 on 2023-01-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0017_spare_part_checked_count_spare_part_max_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare_part',
            name='sap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
