# Generated by Django 4.1 on 2023-01-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0020_alter_spare_part_sap_count_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='sap_count_total',
            field=models.PositiveIntegerField(default=0, null='true'),
        ),
    ]
