# Generated by Django 4.1 on 2023-02-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0022_alter_spare_part_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='for_order',
            field=models.PositiveIntegerField(default=0, null='true'),
        ),
    ]
