# Generated by Django 4.1 on 2023-03-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0023_alter_spare_part_for_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='sap_Code2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spare_part',
            name='sap_analog',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
