# Generated by Django 4.1 on 2023-03-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0025_alter_spare_part_sap_code2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging_equipment',
            name='criticality',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
