# Generated by Django 4.1 on 2023-03-28 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0026_belonging_equipment_criticality'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_equipment', models.CharField(max_length=90)),
                ('count_part', models.PositiveSmallIntegerField(default=0)),
                ('be_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.belonging_equipment')),
            ],
        ),
    ]
