# Generated by Django 4.1 on 2023-03-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0027_nodeeq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeEq',
        ),
    ]
