# Generated by Django 4.1 on 2023-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0028_delete_nodeeq'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging_equipment',
            name='in_node_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
