# Generated by Django 4.1 on 2023-03-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0030_modeq_nodeeq_spec_workp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModEq',
        ),
        migrations.DeleteModel(
            name='NodeEq',
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
        migrations.DeleteModel(
            name='WorkP',
        ),
    ]
