# Generated by Django 4.1 on 2023-03-28 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0031_delete_modeq_delete_nodeeq_delete_spec_delete_workp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_eq_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_proc_name', models.CharField(max_length=50)),
                ('work_proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.spec')),
            ],
        ),
        migrations.CreateModel(
            name='NodeEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_eq_name', models.CharField(max_length=90)),
                ('node_eq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.modeq')),
            ],
        ),
        migrations.AddField(
            model_name='modeq',
            name='model_eq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spareparts1.workp'),
        ),
    ]
