# Generated by Django 4.1 on 2023-03-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0032_modeq_spec_workp_nodeeq_modeq_model_eq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeq',
            old_name='model_eq',
            new_name='work_proc_name',
        ),
        migrations.RenameField(
            model_name='nodeeq',
            old_name='node_eq',
            new_name='model_eq_name',
        ),
        migrations.RenameField(
            model_name='workp',
            old_name='work_proc',
            new_name='spec_name',
        ),
    ]
