# Generated by Django 4.1 on 2023-03-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0035_nodesonequipment_belonging_equipment_test_node_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belonging_equipment_test',
            name='node_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts1.nodesonequipment'),
        ),
    ]
