# Generated by Django 4.1 on 2023-03-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0038_remove_belonging_equipment_test_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodesonequipment',
            name='node_name',
        ),
    ]
