# Generated by Django 4.1 on 2023-03-29 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0039_remove_nodesonequipment_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging_equipment_test',
            name='node_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='spareparts1.nodesonequipment'),
        ),
        migrations.AddField(
            model_name='nodesonequipment',
            name='node_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spareparts1.nodeeq'),
        ),
    ]
