# Generated by Django 4.1 on 2023-03-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0042_delete_nodesonequipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeq',
            name='work_proc_name',
        ),
        migrations.RemoveField(
            model_name='nodeeq',
            name='model_eq_name',
        ),
        migrations.RemoveField(
            model_name='workp',
            name='spec_name',
        ),
        migrations.DeleteModel(
            name='Belonging_equipment_test',
        ),
        migrations.DeleteModel(
            name='ModEq',
        ),
        migrations.DeleteModel(
            name='NodeEq',
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
        migrations.DeleteModel(
            name='WorkP',
        ),
    ]
