# Generated by Django 4.1 on 2023-03-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0045_alter_belonging_equipment_test_node_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeq',
            name='work_proc_name',
        ),
        migrations.RemoveField(
            model_name='nodeeq',
            name='model_eq_name',
        ),
        migrations.RemoveField(
            model_name='nodesonequipment',
            name='node_name',
        ),
        migrations.RemoveField(
            model_name='nodesonequipment',
            name='part_count',
        ),
        migrations.RemoveField(
            model_name='workp',
            name='spec_name',
        ),
        migrations.DeleteModel(
            name='Belonging_equipment_test',
        ),
        migrations.DeleteModel(
            name='ModEq',
        ),
        migrations.DeleteModel(
            name='NodeEq',
        ),
        migrations.DeleteModel(
            name='NodesOnEquipment',
        ),
        migrations.DeleteModel(
            name='Spec',
        ),
        migrations.DeleteModel(
            name='WorkP',
        ),
    ]
