# Generated by Django 4.1 on 2023-03-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0046_remove_modeq_work_proc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='start_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='node_equipment',
            field=models.CharField(max_length=50),
        ),
    ]
