# Generated by Django 4.1 on 2023-04-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0047_equipment_start_index_alter_equipment_node_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='belonging_equipment',
            name='on_model_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
