# Generated by Django 4.1 on 2023-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0048_belonging_equipment_on_model_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.PositiveIntegerField(default=0, null='true'),
            preserve_default='true',
        ),
    ]
