# Generated by Django 4.1 on 2023-07-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0049_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_from_excel',
            name='kritichnost_zapch_imp',
            field=models.PositiveIntegerField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='import_from_excel',
            name='srok_postavki_imp',
            field=models.PositiveIntegerField(null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='spare_part',
            name='delivery_time',
            field=models.PositiveIntegerField(null='true'),
            preserve_default='true',
        ),
    ]
