# Generated by Django 4.1 on 2023-10-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0051_alter_equipment_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_from_excel',
            old_name='vliyanie_imp',
            new_name='kritichnost_obor_imp',
        ),
    ]
