# Generated by Django 4.1 on 2023-10-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0053_remove_import_from_excel_number_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='edin_izm_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='model_obor_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='naimen_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='proc_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='proizv_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='tip_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='uzel_imp',
            field=models.CharField(max_length=190, null='true'),
        ),
    ]
