# Generated by Django 4.1 on 2023-10-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0056_alter_import_from_excel_edin_izm_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='localiz_imp',
            field=models.CharField(max_length=290, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='meh_el_imp',
            field=models.CharField(max_length=290, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='uzel_imp',
            field=models.CharField(max_length=290, null='true'),
        ),
    ]
