# Generated by Django 4.1 on 2023-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0060_alter_import_from_excel_edin_izm_imp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='localiz_imp',
            field=models.CharField(max_length=250, null='true'),
        ),
    ]
