# Generated by Django 4.1 on 2023-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0068_alter_import_from_excel_localiz_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='proizv_imp',
            field=models.CharField(max_length=50, null='true'),
        ),
    ]
