# Generated by Django 4.1 on 2023-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0072_alter_import_from_excel_proizv_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='proc_imp',
            field=models.CharField(max_length=90, null='true'),
        ),
    ]
