# Generated by Django 4.1 on 2023-10-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0074_alter_import_from_excel_model_obor_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='edin_izm_imp',
            field=models.CharField(max_length=11, null='true'),
        ),
        migrations.AlterField(
            model_name='import_from_excel',
            name='uzel_imp',
            field=models.CharField(max_length=291, null='true'),
        ),
    ]
