# Generated by Django 4.1 on 2023-10-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0076_alter_import_from_excel_meh_el_imp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_from_excel',
            name='naimen_imp',
            field=models.CharField(max_length=150, null='true'),
        ),
    ]
