# Generated by Django 4.1 on 2023-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0080_alter_equipment_node_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare_part',
            name='manufacturer',
            field=models.CharField(default='', max_length=90),
        ),
    ]
