# Generated by Django 4.1 on 2023-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0081_alter_spare_part_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='count_model_equipment',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
