# Generated by Django 4.2 on 2024-07-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts1', '0082_equipment_count_model_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='count_model_equipment',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
